app: wis
env: production
namespace: default
chart:
  repository: https://chart.onechart.dev
  name: onechart
  version: 0.41.0
values:
  containerPort: 9000
  gitRepository: gimlet-io/github-actions-integration-sample
  gitSha: '{{ .GITHUB_SHA }}'
  image:
    repository: ghcr.io/gimlet-io/wis
    tag: '{{ .SHA }}'
  ingress:
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      kubernetes.io/ingress.class: nginx
    host: wis.turbopizza.net
    tlsEnabled: true
  resources:
    requests:
      cpu: 20m
      memory: 20Mi
strategicMergePatches: ""
json6902Patches: []
manifests: ""
