pipeline:
  build:
    image: docker
    commands:
      - echo "This is the build"
  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      registry: "https://ghcr.io"
      repo: ghcr.io/gimlet-io/wis
      dockerfile: Dockerfile
      platforms: linux/amd64
      tag: ${CI_COMMIT_SHA}  
  deploy-staging:
    image: ghcr.io/gimlet-io/woodpecker-plugin:03ea7513ba92740916a2deade74c3e376a94ccaf
    when:
      branch: main
      event: push  
    secrets: [gimlet_server, gimlet_token]
    # settings:
      # debug: true
