pipeline:
  build:
    image: debian:stable-slim
    commands:
      - echo "This is the build"
  docker:
    image: debian:stable-slim
    commands:
     - echo $${DOCKER_USERNAME}
     - echo $${DOCKER_PASSWORD}
    secrets: [ docker_username, docker_password ]
  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: ghcr.io/gimlet-io/gais
      dockerfile: Dockerfile
      platforms: linux/amd64
      tag: ${CI_COMMIT_SHA} 
    when:
      event: push
