pipeline:
  build:
    image: docker
    secrets: [gimlet_server, gimlet_token]
    commands:
      - echo "This is the build"
      - printenv | grep CI
      - printenv | grep CI | grep -v '=$' | awk '$0="--var "$0'
  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      registry: "https://ghcr.io"
      repo: ghcr.io/gimlet-io/wis
      dockerfile: Dockerfile
      platforms: linux/amd64
      tag: ${CI_COMMIT_SHA}
  deploy-preview:
    image: ghcr.io/gimlet-io/woodpecker-plugin:8bf1f3c51758bfeba3e000f8202f8b1af8c6a824
    when:
      branch: [feature/*, bugfix/*]
      event: push  
    secrets: [gimlet_server, gimlet_token]
    settings:
      deploy: true
      env: preview
      app: wis
      wait: true
  deploy-staging:
    image: ghcr.io/gimlet-io/woodpecker-plugin:8bf1f3c51758bfeba3e000f8202f8b1af8c6a824
    when:
      branch: main
      event: push  
    secrets: [gimlet_server, gimlet_token]
    settings:
      deploy: true
      env: staging
      app: wis
      wait: true
  deploy-production:
    image: ghcr.io/gimlet-io/woodpecker-plugin:8bf1f3c51758bfeba3e000f8202f8b1af8c6a824
    when:
      tag: v*
      event: tag  
    secrets: [gimlet_server, gimlet_token]
    settings:
      deploy: true
      env: production
      app: wis
      wait: true
