pipeline:
  build:
    image: debian:stable-slim
    secrets: [docker_username, docker_password]
    commands:
      - echo "This is the build"
      - echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      repo: ghcr.io/gimlet-io/gais
      dockerfile: Dockerfile
      platforms: linux/amd64
      tag: ${CI_COMMIT_SHA}
      debug: true    
    when:
      event: push
