pipeline:
  build:
    image: docker
    secrets: [docker_username, docker_password]
    commands:
      - echo "This is the build"
      - echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
  docker-build:
    image: woodpeckerci/plugin-docker-buildx
    secrets: [docker_username, docker_password]
    settings:
      registry: "https://ghcr.io"
      repo: ghcr.io/gimlet-io/wis
      dockerfile: Dockerfile
      platforms: linux/amd64
      tag: ${CI_COMMIT_SHA}  
    when:
      event: push
